FROM public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

RUN yum install -y gcc python-setuptools python-devel postgresql-devel libyaml-devel

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY setup.py .
COPY bin/* .
COPY bin/ bin/
COPY openforge ./openforge
RUN python setup.py install

CMD ["openforge.app.index.lambda_handler"]
