FROM public.ecr.aws/lambda/python:3.11

WORKDIR /app

RUN yum install -y postgresql-devel libpq-devel python3-devel libyaml-devel

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY setup.py .
COPY bin ./bin
COPY openforge ./openforge
RUN python3 setup.py install

COPY api/index.py ./index.py

CMD ["index.lambda_handler"]
