version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: openforge
      POSTGRES_PASSWORD: openforge
      POSTGRES_DB: openforge
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

