[pytest]
testpaths = tests
norecursedirs = db-data .git .next node_modules
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning:botocore.* 