import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import HeaderApp from "@/components/header-app";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<SidebarProvider
					style={
						{
							"--sidebar-width": "350px",
						} as React.CSSProperties
					}
				>
					<AppSidebar />
					<SidebarInset>
						<HeaderApp />
						{children}
					</SidebarInset>
				</SidebarProvider>
			</body>
		</html>
	);
}
